services:
  shopping:
    build:
      context: ../..
      dockerfile: Sample/ShoppingListSample/Sample.Api/Dockerfile
    ports: ["127.0.0.1:8081:8081"]
    volumes:
      - shopping-readmodels:/data
      - shopping-events:/root/.config/troolio-samples-shopping
volumes:
  shopping-readmodels:
  shopping-events:
