<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <Version>$(TroolioExtensionsVersion)</Version>
    <Authors>Fifty3North (F3N Limited)</Authors>
    <Description>gRPC event persistence for ordinary Troolio actors using KurrentDB.</Description>
    <PackageProjectUrl>https://fifty3north.github.io/troolio-docs/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Fifty3North/troolio.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>package-readme.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Troolio.Core" Version="$(TroolioCoreVersion)" />
    <PackageReference Include="KurrentDB.Client" Version="1.4.1" />
    <None Include="package-readme.md" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>
