version: '3.7'

services:
  shopping-api:
    container_name: shopping-api
    image: ${DOCKER_REGISTRY-}shopping-api
    build:
      context: ../../
      dockerfile: Sample/ShoppingList/ShoppingList.Api/Dockerfile
    depends_on: 
      - "shopping-host"
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=http://+:8081
    ports:
      - "8081:8081"
    networks:
      - Shopping-Net
  shopping-host:
    container_name: shopping-host
    image: ${DOCKER_REGISTRY-}shopping-host
    expose: 
      - "9000"
      - "9001"
    ports:
      - "8888:8888"
    build:
      context: ../../
      dockerfile: Sample/ShoppingList/ShoppingList.Host/Dockerfile
    depends_on: 
      - "azurite"
      - "db"
      - "eventstore"
    networks:
      - Shopping-Net
  azurite:
    container_name: shopping-azurite
    # bug in Azurite version 3.18.0 means upserts fail with 404 error
    image: mcr.microsoft.com/azure-storage/azurite:3.17.1
    restart: always
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    networks:
      - Shopping-Net
  eventstore:
    container_name: shopping-eventstore
    image: "eventstore/eventstore:latest"
    environment:
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_RUN_PROJECTIONS=System
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113" 
    networks:
      - Shopping-Net
  db:
    container_name: shopping-db
    image: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_ROOT_HOST=%
    ports:
      - "13306:3306"
    networks:
      - Shopping-Net
networks: 
  Shopping-Net:
    driver: bridge
    name: Shopping-Net