using Microsoft.Extensions.Configuration;
using Sample.Shared.ActorInterfaces;
using Sample.Shared.Commands;
using Sample.Shared.Events;
using Sample.Shared.Exceptions;
using Sample.Shared.InternalCommands;
using System.Collections.Immutable;
using Troolio.Core;
using Troolio.Core.Stateful;
using Troolio.Stores;

namespace Sample.Host.App.ShoppingList;

public class AllShoppingListsActor : StatefulActor<AllShoppingListsState>, IAllShoppingListsActor
{
    public AllShoppingListsActor(IStore store, IConfiguration configuration) : base(store, configuration)
    { 
         this.State = new AllShoppingListsState( ImmutableDictionary<string, Guid>.Empty);
    }

    #region Commands ...
    public IEnumerable<Event> Handle(AddShoppingList command)
    {
        // Generate code
        // TODO - *** This needs to be a core field type, "AutogeneratedString4" ***
        string joinCode = Guid.NewGuid().ToString().Substring(0, 4);

         return new[] { new ShoppingListAdded(command.ListId, joinCode, command.Headers) };
    }
    public IEnumerable<Event> Handle(JoinListUsingCode command)
    {
        if (command.payload.Code == null || !this.State.Lists.ContainsKey(command.payload.Code))
        {
            throw new InvalidJoinCodeException();
        }

        yield return new ListJoinedUsingCode(this.State.Lists[command.payload.Code], command.Headers);
    }
    #endregion

    #region Events ...
    public void On(ListJoinedUsingCode _) { } // Stub this non-state changing event
    public void On(ShoppingListAdded ev) => this.State = this.State with { Lists = State.Lists.Add(ev.joinCode, ev.ListId) };
    #endregion
}
