using Microsoft.Extensions.Configuration;
using Sample.Shared.ActorInterfaces;
using Sample.Shared.Commands;
using Sample.Shared.Events;
using Sample.Shared.Exceptions;
using Sample.Shared.InternalCommands;
using System.Collections.Immutable;
using Troolio.Core;
using Troolio.Core.Stateful;
using Troolio.Stores;

namespace Sample.Host.App.ShoppingList;

public class AllShoppingListsActor : StatefulActor<AllShoppingListsState>, IAllShoppingListsActor
{

    public AllShoppingListsActor(IStore store, IConfiguration configuration) : base(store, configuration)
    {
         State = new AllShoppingListsState(ImmutableDictionary<string, Guid>.Empty);
    }

    #region Commands ...
    public IEnumerable<Event> Handle(AddShoppingList command)
    {
        if (State.Lists.Values.Contains(command.ListId)) return [];

        // Generate code
        // TODO - *** This needs to be a core field type, "AutogeneratedString4" ***
        string joinCode = command.JoinCode;
        if (string.IsNullOrEmpty(joinCode) || State.Lists.ContainsKey(joinCode)) throw new InvalidOperationException("Join code must be unique.");

        return new[] { new ShoppingListAdded(command.ListId, joinCode, command.Headers) };
    }
    public IEnumerable<Event> Handle(JoinListUsingCode command)
    {
        if (command.Payload.JoinCode == null || !this.State.Lists.ContainsKey(command.Payload.JoinCode))
        {
            throw new InvalidJoinCodeException();
        }

        yield return new ListJoinedUsingCode(this.State.Lists[command.Payload.JoinCode], command.Headers);
    }
    #endregion

    #region Events ...
    public void On(ListJoinedUsingCode _) { } // Stub this non-state changing event
    public void On(ShoppingListAdded ev) => this.State = this.State with { Lists = State.Lists.Add(ev.JoinCode, ev.ListId) };
    #endregion

    #region Queries
    public string Handle(AuthorRequestedJoinCode query) => State.Lists.FirstOrDefault(l => l.Value == query.ListId).Key;
    #endregion
}
