# This will build a release version of troolio.projection.entityframework and publish the nuget package
name: Troolio_EntityFramework_Release

# Controls when the workflow will run
on:
    push:
        tags:
            - 'Troolio.Projection.EntityFramework_[0-9]+.[0-9]+.[0-9]+'

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: Install dependencies
          run: dotnet restore Projections/Troolio.Projection.EntityFramework/Troolio.Projection.EntityFramework.csproj
      
        - name: Build
          run: dotnet build --configuration Release --no-restore Projections/Troolio.Projection.EntityFramework/Troolio.Projection.EntityFramework.csproj

        - name: Parser
          uses: johngeorgewright/parse-version-action@v1.0.2
          id: parser
          with:
            ref: ${{ github.ref }}
            trim-start: Troolio.Projection.EntityFramework_

        - name: Create NuGet Package
          run: dotnet pack --configuration Release Projections/Troolio.Projection.EntityFramework/Troolio.Projection.EntityFramework.csproj --no-build -p:PackageVersion=${{ steps.parser.outputs.version }}

        - name: Publish the package to nuget
          run: dotnet nuget push Projections/Troolio.Projection.EntityFramework/*/**/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
