# This will build a release version of Troolio.Stores.EventStore and publish the nuget package
name: Troolio_Stores_Marten_Release

# Controls when the workflow will run
on:
    push:
        tags: 
            - 'Troolio.Stores.Marten_[0-9]+.[0-9]+.[0-9]+'

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: Install dependencies
          run: dotnet restore Stores/Troolio.Stores.Marten/Troolio.Stores.Marten.csproj
      
        - name: Build
          run: dotnet build --configuration Release --no-restore Stores/Troolio.Stores.Marten/Troolio.Stores.Marten.csproj

        - name: Parser
          uses: johngeorgewright/parse-version-action@v1.0.2
          id: parser
          with:
            ref: ${{ github.ref }}
            trim-start: Troolio.Stores.Marten_

        - name: Create NuGet Package
          run: dotnet pack --configuration Release Stores/Troolio.Stores.Marten/Troolio.Stores.Marten.csproj --no-build -p:PackageVersion=${{ steps.parser.outputs.version }}

        - name: Publish the package to nuget
          run: dotnet nuget push Stores/Troolio.Stores.Marten/*/**/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate