<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
	  <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Troolio.Core" Version="$(TroolioCoreVersion)" />
    <PackageReference Include="Microsoft.Orleans.Sdk" Version="$(OrleansVersion)" PrivateAssets="all" />
  </ItemGroup>

</Project>
