<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
	  <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\trool.io\Troolio.Core\Troolio.Core.csproj" />
    <ProjectReference Include="..\..\..\..\trool.io\Orleankka\Orleankka.csproj" />
    <ProjectReference Include="..\..\..\..\trool.io\Orleankka.Runtime\Orleankka.Runtime.csproj" />
    <ProjectReference Include="..\..\..\..\trool.io\Orleankka.TestKit\Orleankka.TestKit.csproj" />
  </ItemGroup>

</Project>
